<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_field_widget_form_alter().
 */
function epa_viewsreference_field_widget_form_alter(array &$element, FormStateInterface $form_state, array $context) {
  $plugin_id = $context['widget']->getPluginId();

  if ($plugin_id === 'viewsreference_select') {

    // Use "details" containers since they are themed better in layout builder UI
    if (isset($element["options"]["exposed_filters"]['#type'])) {
      $element["options"]["exposed_filters"]['#type'] = 'details';
      $element["options"]["exposed_filters"]['#open'] = TRUE;
    }
    if (isset($element["options"]["exposed_sorts"]['#type'])) {
      $element["options"]["exposed_sorts"]['#type'] = 'details';
      $element["options"]["exposed_sorts"]['#open'] = TRUE;
    }

    // Hide the control that allows users to expose filters on dynamic lists.
    if (isset($element["options"]["exposed_filters"]["vr_exposed_filters_visible"])) {
      $element["options"]["exposed_filters"]["vr_exposed_filters_visible"]['#access'] = FALSE;
    }
  }
}
