#!/bin/bash

## Description: Replace database
## Usage: epa-import
## Example: "ddev epa-import "


select FILENAME in /var/db/*;
do
  case $FILENAME in
    "$QUIT")
      break
      ;;
    *)
    echo "You have Selected: $FILENAME ($REPLY) Please type 'q' and press enter."
    dump_name="$FILENAME"
    ;;
  esac
done;

rm -rf /var/lib/mysql
tar xzf $dump_name  -C /var/lib/mysql
