#!/bin/bash

## Description: Exports the current database
## Usage: epa-export
## Example: "ddev epa-export "
cd /var/lib/mysql
FILENAME=epa-backup-local-`date +%Y%m%d`.tgz
tar -pvczf $FILENAME .
mv $FILENAME /var/db/$FILENAME

