#!/bin/bash

# This script downloads AWS Parameter Store values and saves them as files to the checkout
# prior to the Buildkite command step executing, making it ideal to load configuration
# files.

set -euo pipefail

echo "~~~ :aws: Loading parameters..."

# Usage:
#   get-parameter NAME FILE
#
# NAME: The name of a Parameter Store parameter. The prefix /buildkite/terraform is
#       automatically applied.
# FILE: The destination file in the infrastructure/terraform directory.
#
# This function copies an AWS Parameter Store parameter into a destination file. This is
# mostly intended to be used for downloading data to be used during the Terraform-related
# steps.
get-parameter() {
  local -r name="/buildkite/terraform/$1"
  local -r file="infrastructure/terraform/$2"

  aws ssm get-parameter --name "$name" |
    jq -r '.Parameter.Value' \
      >"$file"

  echo "Loaded parameter $name into $file"
}

get-parameter backend-config backend.config
get-parameter "variables-$WEBCMS_ENVIRONMENT" terraform.tfvars
