#!/bin/bash

## Description: Setup minio
## Usage: aws-setup
## Example: "ddev aws-setup "
aws --endpoint  http://minio:9000 s3 mb s3://drupal
aws --endpoint http://minio:9000 s3api put-bucket-policy --bucket drupal --policy "$(cat /tmp/minio/policy.json)"
