env:
  WEBCMS_ENVIRONMENT: ${WEBCMS_ENVIRONMENT}
  WEBCMS_SITE: ${WEBCMS_SITE}
  WEBCMS_IMAGE_TAG: ${WEBCMS_IMAGE_TAG}
  WEBCMS_REPO_URL: ${WEBCMS_REPO_URL}

steps:
  # Apply any pending updates to the VPC for this environment
  - label: ":pipeline: :terraform: network"
    command: buildkite-agent pipeline upload .buildkite/terraform.apply.yml

    env:
      WEBCMS_ENVIRONMENT: ${WEBCMS_ENVIRONMENT}
      WEBCMS_TF_MODULE: network
      WEBCMS_SSM_NAMESPACE: /terraform/${WEBCMS_ENVIRONMENT}/network

  # Wait on the above to to succeed before continuing
  - wait: ~

  # Next, we apply pending updates to the infrastructure (i.e., AWS resources & services).
  # This step has to wait for the VPC due to the dependency on networking component IDs
  # (subnets, security groups, and the VPC itself).
  - label: ":pipeline: :terraform: infrastructure"
    command: buildkite-agent pipeline upload .buildkite/terraform.apply.yml

    env:
      WEBCMS_ENVIRONMENT: ${WEBCMS_ENVIRONMENT}
      WEBCMS_TF_MODULE: infrastructure
      WEBCMS_SSM_NAMESPACE: /terraform/${WEBCMS_ENVIRONMENT}/infrastructure
