# This is the primary pipeline for builds. It dispatches different pipelines based on
# which branch this build is for. Feature branches only perform basic validation steps,
# whereas for the main and integration branches, we perform a full deployment.

env:
  # Common image tag used across steps
  WEBCMS_IMAGE_TAG: $BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER

  # Base URL for image repositories
  WEBCMS_REPO_URL: 316981092358.dkr.ecr.us-east-1.amazonaws.com

steps:
  - label: ":pipeline: Feature"
    if: |
      (build.branch != "main" || build.branch != "integration") ||
      build.pull_request.id != null

    command: buildkite-agent pipeline upload .buildkite/feature.yml
    env:
      # We specify the staging environment since most feature branches target main instead
      # of integration
      WEBCMS_ENVIRONMENT: stage
      WEBCMS_WORKSPACE: stage

  # Upload the deploy pipeline from integration to the dev environment, disregarding PRs
  - label: ":pipeline: Dev"
    if: build.branch == "integration" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/deploy.yml
    env:
      WEBCMS_ENVIRONMENT: dev
      WEBCMS_WORKSPACE: default

  # Upload the deploy pipeline from main to the stage environment, disregarding PRs
  - label: ":pipeline: Stage"
    if: build.branch == "main" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/deploy.yml
    env:
      WEBCMS_ENVIRONMENT: stage
      WEBCMS_WORKSPACE: stage

  # Also on the main branch, deploy to the Spanish-language test environment
  - label: ":pipeline: Español"
    if: build.branch == "main" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/deploy.yml
    env:
      WEBCMS_ENVIRONMENT: espanol
      WEBCMS_WORKSPACE: espanol
