env:
  # Common image tag used across steps
  WEBCMS_IMAGE_TAG: $BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER

  # Base URL for image repositories
  WEBCMS_REPO_URL: 316981092358.dkr.ecr.us-east-1.amazonaws.com

steps:
  - label: ":docker: Build images"
    command: bash .buildkite/docker-build.sh
    key: build

    # Limit build concurrency to 1 per branch: this throttles overlapping builds
    concurrency_group: epa-webcms-d8/build-$BUILDKITE_BRANCH
    concurrency: 1

    plugins:
      # Assume cross-account build role
      - cultureamp/aws-assume-role#28c5ceccb0d5cbef2c592a57579fd4c6a2869bd7:
          role: arn:aws:iam::316981092358:role/BuildkiteRoleForImageBuilds
      # Log in to ECR repositories
      # NB. This is not the latest version of the plugin, but we have to downgrade in order
      # to play nice with aws-assume-role.
      - ecr#v1.2.0:
          login: true
          no-include-email: true

  - label: ":terraform: Deploy templates"
    key: deploy

    # Only build on the master branch, and only if this isn't a pull request
    if: build.branch == "EPAD8-432-setup-continued" && build.pull_request.id == null

    # Only allow one deployment at a time
    concurrency_group: epa-webcms-d8/deploy
    concurrency: 1

    # Run only if the build step succeeded
    depends_on: build

    plugins:
      # Assume the Terraform role for maximum permissions
      - cultureamp/aws-assume-role#28c5ceccb0d5cbef2c592a57579fd4c6a2869bd7:
          role: arn:aws:iam::316981092358:role/BuildkiteRoleForTerraform
          # Use a 30-minute duration for credentials to minimize the time spent in this
          # nearly-administrative role
          duration: 1800
      # Load AWS parameters: we do this here because hashicorp/terraform does not include
      # the AWS CLI, so we need to obtain these configuration values before executing
      # Terraform in Docker.
      - ./.buildkite/plugins/aws-parameters:
          params:
            - name: /buildkite/terraform/backend-config
              file: infrastructure/terraform/backend.config
            - name: /buildkite/terraform/variables
              file: infrastructure/terraform/terraform.tfvars
      # Perform a Terraform apply in the provided Docker image
      - docker#v3.5.0:
          image: hashicorp/terraform:0.12.24
          entrypoint: /bin/sh
          command: [.buildkite/deploy-terraform.sh]
          environment:
            # Forward image tag
            - WEBCMS_IMAGE_TAG
            # Forward STS-assumed credentials
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_SESSION_TOKEN
      - artifacts#v1.3.0:
          upload:
            - from: infrastructure/terraform/out.plan
              to: out.plan
            - from: infrastructure/terraform/drushvpc.json
              to: drushvpc.json

  - label: ":ecs: Run Drush updates"
    command: bash .buildkite/run-drush.sh

    # Only build on the master branch, and only if this isn't a pull request
    if: build.branch == "EPAD8-432-setup-continued" && build.pull_request.id == null

    # Run only if the previous deploy step succeeded
    depends_on: deploy

    # Only allow one Drush update at a time
    concurrency_group: epa-webcms-d8/update
    concurrency: 1

    plugins:
      # Download the Drush AWSVPC configuration
      - artifacts#v1.3.0:
          download: drushvpc.json
      # Assume our ECS task management role
      - cultureamp/aws-assume-role#28c5ceccb0d5cbef2c592a57579fd4c6a2869bd7:
          role: arn:aws:iam::316981092358:role/BuildkiteRoleForECSTasks
