# DEPRECATED: Buildkite pipelines are no longer used. All builds and deployments run in GitLab CI (.gitlab-ci.yml). This file is retained for historical reference. Last updated: 2025-10-09.
# This is the primary pipeline for builds. It dispatches different pipelines based on
# which branch this build is for. Feature branches only perform basic validation steps,
# whereas for the main and integration branches, we perform a full deployment.

env:
  # Common image tag used across steps
  WEBCMS_IMAGE_TAG: $BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER

  # Base URL for image repositories
  WEBCMS_REPO_URL: 316981092358.dkr.ecr.us-east-2.amazonaws.com

steps:
  # For all feature branches, only perform build & validation steps. Nothing is deployed
  # in this pipeline.
  - label: ":pipeline: Feature"
    if:
      build.branch != "integration" &&
      build.branch != "main" &&
      build.branch != "release" &&
      build.branch != "live"

    command: buildkite-agent pipeline upload .buildkite/feature.yml
    env:
      # We specify the staging site since most feature branches target main instead
      # of integration
      WEBCMS_ENVIRONMENT: preproduction
      WEBCMS_SITE: main

  # Steps below this line are gated by build.branch matching a specific branch, and
  # build.pull_request_id == null, which prevents Buildkite from doing deployments if the
  # targeted branch is the source in a PR. (This is a rare but observed occurrence.)

  - label: ":pipeline: Infrastructure"
    if: build.branch == "main" && build.pull_request.id == null

    command: buildkite-agent pipeline upload .buildkite/infrastructure.yml
    env:
      WEBCMS_ENVIRONMENT: preproduction

  # When the infrastructure pipeline is uploaded, we have to wait on it to
  # succeed before deploying the application, as some resources may be
  # created/modified that are needed for deployments. Note that if the pipeline
  # is skipped, this wait incurs no penalty.
  - wait: ~

  # For each of the branches we deploy, run the webcms.yml pipeline. (See below
  # for the USWDS environment.)
  - label: ":pipeline: WebCMS (${BUILDKITE_BRANCH})"
    if:
      build.pull_request.id == null && (
        build.branch == "integration" ||
        build.branch == "main" ||
        build.branch == "release" ||
        build.branch == "live"
      )

    command: buildkite-agent pipeline upload .buildkite/webcms.yml
    env:
      WEBCMS_ENVIRONMENT: preproduction
      WEBCMS_SITE: ${BUILDKITE_BRANCH}
