#!/bin/sh

set -eu

# This script performs a Terraform apply using the "out.plan" that was generated by the
# previous script (terraform-plan.sh). All builds perform a plan step in order to have a
# record of potential infrastructure changes, and only deployment builds will run this
# script.

# Like the plan script, we enter the Terraform directory and download plugins
cd infrastructure/terraform
terraform init -input=false -backend-config=backend.config

# Apply Terraform plan generated in previous step
terraform apply -input=false out.plan

# Capture the Drush AWSVPC task configuration for the Drush update step
terraform output drush-task-config > drushvpc.json
