filter_settings.media_inline_embed:
  type: filter
  label: 'Media Embed'
  mapping:
    default_view_mode:
      type: string
      label: 'The view mode that is used by default'
    allowed_media_types:
      type: sequence
      label: 'Media types selectable in the Media Library'
      sequence:
        type: string
        label: 'Media type'
    allowed_view_modes:
      type: sequence
      label: 'View modes selectable in the "Edit media" dialog'
      sequence:
        type: string
        label: 'View mode'

# Plugin \Drupal\media_inline_embed\Plugin\CKEditor5Plugin\DrupalInlineMedia
ckeditor5.plugin.media_library_inlineMediaLibrary:
  type: mapping
  label: Media Inline
  mapping:
    allow_view_mode_override:
      type: boolean
      label: 'Allow view mode override'
      constraints:
        NotNull: []
