<?php

/**
 * @file
 */

/**
 * Implements hook_user_login().
 */
function f1_sso_user_login($account) {
  // The samlauth module passes around the destination in the RelayState
  // parameter and if it's already planning on redirecting to a non-standard
  // (non- /saml/login) destination then we leave this alone and don't add our
  // own redirect.
  if (\Drupal::service('current_route_match')->getRouteName() === 'samlauth.saml_controller_acs' && $relayState = \Drupal::service('request_stack')->getCurrentRequest()->get('RelayState')) {
    if (stristr($relayState, '/saml/login') === FALSE) {
      return;
    }
  }

  // Only overwrite destination if we don't already have one set.
  if (empty(\Drupal::service('request_stack')->getCurrentRequest()->query->get('destination'))) {
    $url = \Drupal\Core\Url::fromUserInput('/admin/content/my-web-areas');
    $generatedUrl = $url->toString(TRUE);

    $cacheability = new Drupal\Core\Cache\CacheableMetadata();
    $cacheability->setCacheContexts(['user.roles', 'url.query_args']);
     
    $response = new Drupal\Core\Routing\TrustedRedirectResponse($generatedUrl->getGeneratedUrl());
    $response->addCacheableDependency($cacheability);


    \Drupal::request()->query->set('destination', $generatedUrl->getGeneratedUrl());
    \Drupal::service('request_stack')->getCurrentRequest()->attributes->set('_redirect', $response);
  }

}
